apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: download-model
spec:
  params:
    - default: cos-bucket
      description: access key for storage bucket
      name: storage_secret
      type: string
  results:
    - description: the name from the model config.json file
      name: model-name
      type: string
    - description: the name from the model file uploaded by the user
      name: uploaded-file-name
      type: string
  steps:
    - env:
        - name: APIKEY
          valueFrom:
            secretKeyRef:
              key: api-key
              name: $(params.storage_secret)
      image: 'iainubo/ubi-micro-jq:latest'
      name: ''
      resources: {}
      script: >
        cd workspace/output

        eval "export $(cat config.json | jq -r 'to_entries |


        map("\(.key)=\(.value)") | @sh')" 


        eval "export $(echo ${MODEL} | jq -r 'to_entries |


        map("\(.key)=\(.value)") | @sh')"


        echo ${MODEL_NAME} | tee $(results.model-name.path)


        echo ${MODEL_STORE_KEY} | tee $(results.uploaded-file-name.path)


        set | grep MODEL


        TOKEN=`curl -X "POST" "https://iam.cloud.ibm.com/oidc/token" \
            -H 'Accept: application/json' \
            -H 'Content-Type: application/x-www-form-urlencoded' \
            --data-urlencode "apikey=${APIKEY}" \
            --data-urlencode "response_type=cloud_iam" \
            --data-urlencode "grant_type=urn:ibm:params:oauth:grant-type:apikey" \
            -s | jq -r '.access_token'`

        echo "TOKEN retrieved"

        curl
        https://s3.eu-de.cloud-object-storage.appdomain.cloud/roks-cl90hsof0l2k00htpddg-0288/resnet_v1-50.pb
        -H "authorization: bearer $TOKEN" -o resnet_v1-50.pb

        echo "File Downloaded"

        exit 0
  workspaces:
    - description: >-
        Trained model file will be downloaded from object storage to this
        Workspace.
      name: output

